import 'dart:async';
import 'dart:collection';
import 'dart:ffi';
import 'dart:io';
import 'dart:math' as math;
import 'dart:isolate';
import 'package:ffi/ffi.dart';
import 'package:win32/win32.dart';
import 'package:path/path.dart' as path;
import 'package:flutter/foundation.dart';
import 'package:image/image.dart' as img;
import 'package:process_run/shell.dart' as pr;

part 'desktop_helper/constants.dart';
part 'desktop_helper/windowing.dart';
part 'desktop_helper/desktop_icons.dart';
part 'desktop_helper/autorun.dart';
part 'desktop_helper/paths_and_shell.dart';
part 'desktop_helper/clipboard.dart';
part 'desktop_helper/file_copy.dart';
part 'desktop_helper/shortcut_scan.dart';
part 'desktop_helper/icon_types.dart';
part 'desktop_helper/icon_extract/extract_icon.dart';
part 'desktop_helper/icon_extract/jumbo_icon.dart';
part 'desktop_helper/icon_extract/system_icon_index.dart';
part 'desktop_helper/icon_extract/hicon_extract.dart';
part 'desktop_helper/icon_extract/hicon_encode.dart';
part 'desktop_helper/icon_extract/bitmap_png.dart';
part 'desktop_helper/icon_thumbnail_alpha.dart';
part 'desktop_helper/icon_extract_async.dart';
